### ISSUE TITLE
[Feature]: Allow zwave logs to pipe to controller node output

### ISSUE THREAD

**Issue by crxporter** [zwave-js/node-red-contrib-zwave-js#100]
### Contact Details (optional)

goosegoosegoose@duck.com

### What is your idea?

Would like to see the options for zwjs logs to be piped to a second output on controller node. 

Might need a check box for both "to file" and "to second output" - I'm planning only to enable the second output as I don't always want the text file saved. Log level could be the same between "to file" and "to second output" or could be different detail. 

Perhaps just a new drop-down for "log to 2nd output" would do the trick. We can enable and set the log file the same as ever but have a new drop-down to enable 2nd output and choose log level.

### Any more details?

Screenshot of how the NR debug could look:

![unknown-1](https://user-images.githubusercontent.com/38265886/130676686-02f66227-d711-408a-b63c-afd73bbdcb96.png)

### Version

5.0.0

### Node-RED Version

2.0.5

### What hardware are you using?

Raspberry Pi

### Any code to add?

```shell
// format should be json:
format: Winston.format.json()
```

**Comment by marcus-j-davies** [comment]
This is what I am thinking.

![image](https://user-images.githubusercontent.com/55892693/130679238-b56c0a92-afba-4f4e-b938-69a8be5c8983.png)
