### ISSUE TITLE
[Feature]: Ability to generate messages using a factory node

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/node-red-contrib-zwave-js#113]
### What is your idea?

@lurendrejer
> If you ever consider creating some sort of function node, where one can select commands (multi, switch, whatever)

@crxporter, 
As also discussed in discord

Example of its existence.

![image](https://user-images.githubusercontent.com/55892693/135215642-b7fbdd78-44db-432e-b93f-53066e428227.png)

**Comment by crxporter** [comment]
#110 related. Kind of.

**Comment by marcus-j-davies** [comment]
Working Progress.

![image](https://user-images.githubusercontent.com/55892693/135239204-83466487-4c81-407d-9e5e-8a3cd0d9946b.png)

**Comment by crxporter** [comment]
Suggestion... fields for node and params similar to the NR official inject node?

what if my new brightness to set is at `msg.hap.allChars.Brightness` ... I would like to put that in. The input could come direct from NR. 

Also, if "node" input could be the node name, that would really put a smile on my face

**Comment by marcus-j-davies** [comment]
Params and / or node can be taken from a msg part
Params will expect an array object (either strongly typed) or taken from a msg part

**Comment by marcus-j-davies** [comment]
so in your case.

you set params to something like `msg.payload.paramaters`
where parameters will be set prior like this `msg.payload.paramaters = [msg.hap.allChars.Brightness]`

**Comment by crxporter** [comment]
Well I just had a beautiful message all typed out on my phone here with an example json input and whatever... then it disappeared. 

Apart from whether my topic can be a node name (for easy code readability instead of abstract node number) you answered my question and this looks awesome.

**Comment by marcus-j-davies** [comment]
the demo above is nothing more a doodle.
the paths to get the value can be any MSG part
