### ISSUE TITLE
[Help]: How to use ? ValueID

### ISSUE THREAD

**Issue by bakman2** [zwave-js/node-red-contrib-zwave-js#116]
The wiki describes:

_Get the list of ValueIDs for a Node_
```
let Message = {
    payload: {
        mode: "ValueAPI",
        node: 2,
        method: "getDefinedValueIDs",
    }
}
return Message
````

_getValueMetadata_
```
let Message = {
    payload: {
        mode: "ValueAPI",
        node: 2,
        method: "getValueMetadata",
        params: [<ValueID>]
    }
}
return Message
```

I send (preselected 1 specific node) :

```
{
        mode: "ValueAPI",
        method: "getDefinedValueIDs",
    }
```
I get 2 (duplicated) messages back with an array (?)

Lets say I need this part from the array:
```
{"commandClassName":"Thermostat Mode","commandClass":64,"endpoint":0,"property":"manufacturerData","propertyName":"manufacturerData"}
```
I want to get the `getValueMetadata`, so I send:
```
{
        mode: "ValueAPI",
        method: "getValueMetadata",
        params: [64]   
}
```
Result:
```
"ZWaveError: Invalid ValueID passed!"
```

What is the ValueID here, this is not clear to me.

### Any more details?

If this is specific to some hardware or specific software version, please explain here.

### Version

6.1.1

### Node-RED Version

2.0.6

### What hardware are you using?

Other Linux

**Comment by marcus-j-davies** [comment]
Hi @bakman2,

The ValueID must be passed as an object - not an index of the array.


So to get a value for a given ValueID.

```javascript
let MyValueID = {
  "commandClassName": "Thermostat Mode",
  "commandClass": 64,
  "endpoint": 0,
  "property": "manufacturerData",
  "propertyName": "manufacturerData"
}

let Message = {
    payload: {
        mode: "ValueAPI",
        node: 2,
        method: "getValue",
        params: [MyValueID]
    }
}
return Message
```

`getDefinedValueIDs`
gives you the available ValueID's - but you must use them in there entirety (and not based on the index they appear)

**Comment by bakman2** [comment]
Ok thanks that works, that is not what I was expecting (I have never seen an "ID" been described as an object).

So how would I update a "ValueID" ? You pass in the same full object and as value the same full object with updated values ?
I am sorry for the silly questions, but the wiki is not clear to me with examples.

**Comment by marcus-j-davies** [comment]
Yeah, the backend driver refers to an ID - so I do agree its a little confusing.

so, to update a value using the ValueAPI

```javascript
let MyValueID = {
   .......
}

let Message = {
    payload: {
        mode: "ValueAPI",
        node: 2,
        method: "setValue",
        params: [MyValueID, your-value]
    }
}
return Message
```

the CCAPI - is easier, if you want to start there, but by all means go with ValueAPI if you want.

**Comment by marcus-j-davies** [comment]
> I am sorry for the silly questions, but the wiki is not clear to me with examples.
don't be sorry 👍

**Comment by bakman2** [comment]
I want the easiest path, I went in this completely blind, I need to migrate from another zwave node-red node. 
So I wanted to "translate" my previous flow to this. 

Tbh it is easier to look in the cache files than to retrieve the values via node-red.

Now i will look into the "CCAPI". Thanks again for the quick support.

**Comment by marcus-j-davies** [comment]
CCAPI - will require a device to be awake to retrieve data at that moment (or it will be retuned to you, when the device wakes up)

where-as the ValueAPI will use stored values (at least for returning data)
the stored values are updated - when your device send updates of course.

but there is no need for the device to be awake to fetch data if using ValueAPI

CCAPI is easier to use - but it does have draw backs (for battery devices) - at least if you want to fetch data, due to the wait that may occur
