### ISSUE TITLE
New "value notification" event has different identity

### ISSUE THREAD

**Issue by hufftheweevil** [zwave-js/node-red-contrib-zwave-js#12]
I see the update picks up on the new `value notification` event that was added with v6, and it just outputs on this node as a `VALUE_UPDATED` event. At first that seems to work fine, except the new `value notification` event uses a property called `value`, not `newValue`. ([See docs](https://zwave-js.github.io/node-zwave-js/#/api/node?id=quotvalue-notificationquot)) So when you receive a `VALUE_UPDATED` event, you need to figure out if it has a `value` or `newValue` property.

I propose that the `value notification` event should translate to a `VALUE_NOTIFICATION` event on the node, to ensure we handle the output message properly.

**Comment by marcus-j-davies** [comment]
Agreed,

Initially, I wanted to try and keep the events simple in nature, but can see how 'too' simple that one is.

**Comment by marcus-j-davies** [comment]
I have pushed this out already (1.3.1)

I didn't want to be in the situation, where work arounds are deployed on various set ups, then we break it down the line with the new event. Wanted to catch to now.
