### ISSUE TITLE
ERR_DLOPEN_FAILED when installing through node-red

### ISSUE THREAD

**Issue by erikvg01** [zwave-js/node-red-contrib-zwave-js#154]
Hello.  Love the project, have it working well on one system, and it is a life-changing improvement over openzwave.

I have a second system I am attempting to install on.  All modules are loading correctly except the controller.

Errors:
"ERR_DLOPEN_FAILED"     I am getting the error  presented in the Node-Red interface when installing.

"- node-red-contrib-zwave-js:zwave-js : Error: Module did not self-register: '/home/pi/.node-red/node_modules/zwave-js/node_modules/@serialport/bindings/build/Release/bindings.node'."      - this is presented in the node-red console log

node -v : 16.13.0
npm -v:  8.1.4
node-red -v : 2.1.3
Python3.9

I appreciate any guidance.

**Update:**
I was able to correct the issue.  I reinstalled the serialport module through the node-red interface, reinstalled zwave.js through the NR interface which produced a different error.  I then reinstalled zw.js via npm, and it worked properly.  Not certain why the NR interface wouldn't find serialport, but here we are.  All is right in the world, now I rebuild.

**Comment by marcus-j-davies** [comment]
Hi @erikvg01,

Welcome to the project.

serialport is used to speak to the usb dongle, I'm with you, in that not sure NR had a problem installing sierialport.

Glad you got it sorted. Enjoy!

(And thanks)
