### ISSUE TITLE
Interview doesnt complete

### ISSUE THREAD

**Issue by elgerg** [zwave-js/node-red-contrib-zwave-js#16]
**Plugin Version**
1.3.1

**Platform**
Linux, RPI

I have a Z-Stick Gen5 plugged into my PI 3 over a usb extension cable.

Other libs complain about timeouts but have been able to read nodes. This seems to just stay on interview.

Any ideas/suggestions?

![image](https://user-images.githubusercontent.com/24628571/106642862-ce856500-6580-11eb-9de2-72d9ea553e42.png)

Thanks

**Comment by marcus-j-davies** [comment]
is this a battery operated device?

**Comment by marcus-j-davies** [comment]
Any update on this? can it be closed?

**Comment by elgerg** [comment]
Sorry I missed the first update.

I managed to figure out what was going wrong with help from here:
https://loads.pickle.me.uk/2017/04/19/pairing-yale-conexis-lock-and-openzwave/

The key is to pair the device in a secure mode not by using the pair button on the Aeotec Z-Stick Gen5.

Thanks

**Comment by marcus-j-davies** [comment]
Does secure mode work for you with this node?

I recently updated it to use byte arrays (as well as strings)
