### ISSUE TITLE
Can't install in Home Assistant

### ISSUE THREAD

**Issue by nappyjim** [zwave-js/node-red-contrib-zwave-js#17]
I am using node red on home assistant.  When i first went to install it, i had errors because it couldent find make.  With help, I got make on there.   Now here my error logs when trying to install this.

![image](https://user-images.githubusercontent.com/71914301/106676302-35544f80-657c-11eb-9f2d-b2f075f57bda.png)
![image](https://user-images.githubusercontent.com/71914301/106676307-3a190380-657c-11eb-89ad-119972018cf3.png)

**Comment by hufftheweevil** [comment]
I ran into the same problem. You probably need to install `serialport` directly first. Try `npm i serialport@latest`

**Comment by marcus-j-davies** [comment]
Sadly, I'm not that experienced with HA.
As mention by @hufftheweevil try and install `serialport` directly.

`sudo npm install serialport@9.0.6 --unsafe-perm --build-from-source`

**Comment by nappyjim** [comment]
@hufftheweevil how do I get into a command prompt in node-red (launched through home assistant)??  I dont see where/how i would enter 'npm i serialport@latest'

**Comment by marcus-j-davies** [comment]
You can do this via the terminal that putty creates.

`npm install serialport@latest`

**Comment by marcus-j-davies** [comment]
After that I would try and install the node-red plugin via the pallet menu.
normally all this happens automatically, so not sure why HA stops it - again I'm not an expert in HA

**Comment by nappyjim** [comment]
Hmmm, doesnt work.  I know last time I tried command line on my device, I was limited.

Im running HA on their HA "blue" device which is an ODroid N2

![image](https://user-images.githubusercontent.com/71914301/106821762-651a5a80-6643-11eb-9759-25a9ae408f74.png)

**Comment by nappyjim** [comment]
Got it installed by putting in these system_packages in my node red add-on configuration in HA.

![image](https://user-images.githubusercontent.com/71914301/106822078-086b6f80-6644-11eb-9b5d-07275d7660bb.png)

**Comment by sparky073** [comment]
> Got it installed by putting in these system_packages in my node red add-on configuration in HA.
> 
> ![image](https://user-images.githubusercontent.com/71914301/106822078-086b6f80-6644-11eb-9b5d-07275d7660bb.png)

Thank you so much.  Solved same issue for me
