### ISSUE TITLE
[Help]: Can't remove a failed node

### ISSUE THREAD

**Issue by fabnavigator** [zwave-js/node-red-contrib-zwave-js#189]
### Contact Details (optional)

wcmarinelli@gmail.com

### How can we help?

This might be a bug, but I'm note sure so I started here,
Here is what I did:
1. Included a zwave outlet. Works fine with zwavejs node.
2. Shutdown node-red.
3. Did a factory reset on the zwave outlet.
4. Included the zwave outlet into a different zwave primary controller, on another computer.
5. Restarted node-red.
6. Saw the zwave outlet come come up as not ready.
7. Attempted to remove the failed node, but it wanted me to select a node, which I couldn't because it wasn't ready.
8. I eneded up having to reset the controller. This was okay because I'm just in testing mode right now, but would not be okay if I had all my devices incldued.

I think there needs to be a way to select a node in a not ready state.

### Any more details?

If this is specific to some hardware or specific software version, please explain here.

### Version

6.5.5

### Node-RED Version

2.2.2

### What hardware are you using?

Raspberry Pi

**Comment by marcus-j-davies** [comment]
'View in Config Database'
is used to load up the selected device in the zwave-js DB browser.

It opens up a tab in your browser - just make sure you have a selected device (as below)


https://user-images.githubusercontent.com/55892693/155851175-4828d534-9f10-4d7c-b17c-7ec0022d1feb.mov

**Comment by fabnavigator** [comment]
Nothing happens for this device. Does that just mean that it isn't int he database?
![image](https://user-images.githubusercontent.com/16625904/155851348-c8c37492-f0c6-4b21-b3ee-84cd4a7bdb2f.png)

**Comment by marcus-j-davies** [comment]
It will be in the database, as its been identified correctly.
refreshing the device list can 'remove' the selected device - but its information is still displayed, and you can't reselect without selecting another device (but you only have 1 by the looks of it)

These improvements to the UI, are in 6.6.0

**Comment by fabnavigator** [comment]
I closed and reopened by browser and now it works. Thank you.

**Comment by marcus-j-davies** [comment]
No worries - sometimes the UI loses its selected node, selecting a different node will usually resolve it.
should be fixed in 6.6.0

**Comment by fabnavigator** [comment]
I'm looking forward to 6.6.0... I'm just in the initial phase of testing, but so far, I really like what I see, and your responsiveness is more than I could expect.

**Comment by marcus-j-davies** [comment]
v6.6.0 will see a new layout on the UI - to be more inline with the Node RED standards.



https://user-images.githubusercontent.com/55892693/155852545-27a769e7-1d2e-4b92-a9fb-a210499a752b.mov

**Comment by fabnavigator** [comment]
Looks good. I know I'm new to these nodes, but let me know if you need some beta testing. I've got a knack for sniffing out bugs.

**Comment by marcus-j-davies** [comment]
I will be pushing out a BETA once I happy with everything.
@crxporter has wanted this UI re-work for sometime -  he has been involved with the project for sometime.

So - yeah the more BETA testers the better!

**Comment by marcus-j-davies** [comment]
Now in BETA being tested.
