### ISSUE TITLE
Fix : node red log crash

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/node-red-contrib-zwave-js#19]
Re : https://github.com/zwave-js/node-red-contrib-zwave-js/pull/18

**Comment by hufftheweevil** [comment]
Yeah, I guess the underlying error is probably more important to fix. I didn't really dig into why it wasn't able to get the serial ports. Have you already found something?

**Comment by marcus-j-davies** [comment]
one area is permissions (especially with *nix)
I think users need to be apart of the `modem` group, but I'm clutch at straws there

**Comment by marcus-j-davies** [comment]
one area is permissions (especially with *nix)
I think the user running the red process, needs to be apart of the `dialout` group, but I'm clutching at straws here.

**Comment by hufftheweevil** [comment]
I just realized that when I first started using this node, that parameter was just a textbox, wasn't it? I wonder if a better approach is to kind of merge those two things together. Use a text box, but also have an option to list serial ports (if it can) and select one to fill in the text box. Or various other UI technics to do the same thing.

**Comment by marcus-j-davies** [comment]
You can already specify your own, In the drop down choose 'Custom' 
it will list serial ports - but does allow you to type your own

**Comment by hufftheweevil** [comment]
Yea - the problem was that the whole system would crash immediately upon opening the node's properties.

And will do! thanks!
