### ISSUE TITLE
[Question]: heal timeout for battery devices

### ISSUE THREAD

**Issue by fabnavigator** [zwave-js/node-red-contrib-zwave-js#190]
### Contact Details (optional)

wcmarinelli@gmail.com

### What happened?

Started network heal and it only got to 73%. I have three remote controls that are sleeping, but I would have expected them to be skipped after some timeout.

### How to reproduce?

Start network heal
![Untitled](https://user-images.githubusercontent.com/16625904/156929183-fa6b8bb6-b53c-4dbd-9aee-85665ccad20a.png)
.

### Version

6.5.5

### Node-RED Version

2.2.2

### What hardware are you seeing the problem on?

Raspberry Pi

**Comment by crxporter** [comment]
The heal will wait essentially forever for battery devices. When I heal I usually get to 80% within an hour then the final 20% (battery devices) goes for about 12 hours, sometimes a bit longer. I have battery devices mostly set to wake intervals of 12 hours.

**Comment by fabnavigator** [comment]
@crxporter Thank you. I'll leave it running all day and see what happens. Does it makes sense to have an option to skip the sleeping devices?

**Comment by crxporter** [comment]
I don't see any options on the heal network call to the node zwave js api... 

https://zwave-js.github.io/node-zwave-js/#/api/controller?id=beginhealingnetwork

But you can of course just stop it whenever you're bored. The controller will send a message of which nodes were healed so you can check it to be sure the needed things were fixed.

**Comment by fabnavigator** [comment]
Sounds good. Thank you.
