### ISSUE TITLE
[Help]: User Code CC

### ISSUE THREAD

**Issue by ReziioNodeRedAgent** [zwave-js/node-red-contrib-zwave-js#196]
### Contact Details (optional)

richard@reziio.com

### How can we help?

Firstly - thank you for this amazing Node.  I have mostly found it very easy to use.

There is one thing that I can't figure out how to do - I can't get a query to a lock to return all the user codes.

Any assistance on this will be appreciated !

### Any more details?

If this is specific to some hardware or specific software version, please explain here.

### Version

6.5.5

### What hardware are you using?

Raspberry Pi

**Comment by marcus-j-davies** [comment]
Hi @ReziioNodeRedAgent,

The controller node has an option to interview all user codes - **Lock Code Intvw**.

We don't enable this by default, as some locks have so many codes, it results in long interview times.

But the option is there.

After enabling this, reinterview said lock, from the UI (under the selected node Option) once the interview finishes, refresh the page, and hopefully you will find the UI now has the User Codes.

**Comment by ReziioNodeRedAgent** [comment]
Thank you !. Found the option and enabled it so locks now have codes on startup. How do I now query the lock from a node to get the codes from the UI into a flow ?

**Comment by marcus-j-davies** [comment]
Hi @ReziioNodeRedAgent 

There are 2 APIs at your disposal to fetch user Codes:
 - CCAPI
 - ValueAPI

Both have pros and cons:
 - CCAPI
    - Does not keep the local data cache in sync (unless device sends unsolicited updates, when updating said device)
    - Speaks Directly to the device
    - Can fetch payloads without splitting the properties into separate components
    - Uses Raw commands
    
 - ValueAPI
   - Keeps the local data cache updated (the UI Uses it)
   - Does not cause traffic if querying information
   - Payloads are split buy their property/components                  
   - Uses structured objects to address a property (Known as a ValueID)
      A ValueID is not an ID as such - its an object detailing the CC, Endpoint and property a value belongs to             
      
      
In most cases I always suggest using the ValueAPI (the UI can detail the correct ValueID by doubling clicking a Property in the UI)                     

**However!!**
On the basis you want to document User Codes, and their status, the ValueID might be a little cumbersome, so we'll use the CCAPI.

If your device supports >= V2 of User Code CC
```javascript
let Message = {
    payload: {
        mode: "CCAPI",
        node: 26, /* Node */
        cc: 0x63, /* User Code CC */
        method: "get",
        responseThroughEvent: false, /* Wait for response */
        params: [1, true] /* Start User ID, Fetch multiple */
    }
}
return Message
```

The above will yield an array of User Codes (starting from User ID 1)
it will also return a value **nextUserId** meaning you may need to call this again, to fetch the remainder - some devices may only return a max number of codes, so it will differ across device.

See here:
https://zwave-js.github.io/node-zwave-js/#/api/CCs/UserCode?id=get

If you find you get 2 responses back - remove **responseThroughEvent** or set it to **true**

if you want to use the ValueID instead (mostly its the best one) - let me know and I'll explain its use. - The UI can give the ValueIDs - but again may be a little cumbersome of documenting User ID's and status' for each.

I hope the above helps.

**Comment by marcus-j-davies** [comment]
Also see here (along with the ZWave JS docs)
both will help immensely - happy to respond of course 👍 

https://github.com/zwave-js/node-red-contrib-zwave-js/wiki

**Comment by ReziioNodeRedAgent** [comment]
Thank you Marcus ! This is immensely helpful
