### ISSUE TITLE
[Feature]: Create Filters based on debug information

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/node-red-contrib-zwave-js#197]

**Comment by crxporter** [comment]
The goal on this one is to add an button in event filter like "Add filter based on incoming payload"

Then you'd put a debug node on your device, trigger an event, then copy `msg.payload` from the debug panel like this:

![Screen Shot 2022-04-02 at 7 16 30 PM](https://user-images.githubusercontent.com/38265886/161405828-f5d97cf0-44ec-45c1-ac15-09000db2d00f.png)

Then paste into a field somewhere in event filter node and boom - you've got a filter based on this.

**Comment by marcus-j-davies** [comment]
I wasn't able to achieve this yet - But my OCD kills me having it open - we will continue this on Discord 👍
