### ISSUE TITLE
[Help]: Is the Razberry7 Pro supported ?

### ISSUE THREAD

**Issue by Vinisz** [zwave-js/node-red-contrib-zwave-js#217]
### How can we help?

Hi All,
I would like to know if this already works with the Razberry 7 Pro card

### Any more details?

If this is specific to some hardware or specific software version, please explain here.

**Comment by marcus-j-davies** [comment]
Hi @Vinisz,

Based on the fact this card supports the Serial API - you should have no problems in using it.
ZWave JS uses the Serial API, so any ZWave radio that uses said API will be compatible.

obviously you will need to ensure the card you buy, is for your region, but then, some cards allow changing region which can be done in our module.
