### ISSUE TITLE
[Bug]: Watchdog causing a pi 4 reboot when the Aeotec zwave stick is pluged in.

### ISSUE THREAD

**Issue by WarrenEvans** [zwave-js/node-red-contrib-zwave-js#220]
### Contact Details (optional)

warrenevans@xtra.co.nz

### What happened?

I have recently started to use the built in pi4 watchdog. This was done to over come a problem with the pi4 locking up randomly. Everything works fine with the pi4 until I plug in my Aeotec Zwave Stick (Gen 5+). This causes the watchdog to reboot the pi4. I have set the watchdog to 15seconds (max time for pi4). Just to make sure all else was fine, I have run the pi4 for 2 weeks with out the zwave stick, to ensure no other problems. The pi4 runs fine. The use of the watchdog was to fix a lockup problem that happens every few months. As soon as the zwave stick is plugged in, the watchdog reboots in 15 seconds.

I have also tested with the watchdog turned OFF. The pi4 and zwave works fine. Then turn on the watchdog. the pi4 will now reboot every 15 seconds. 

### How to reproduce?

To replicated to the watchdog reboot.
1. With Watchdog turned off. setup a 1 zwave device using a Aeotech Z-Stick with node red.
2. Remove the z-stick from the pi 4.
3. Turn on the watchdog to 15seconds.
4. Check the pi4 is running. 
5. Plug in the z-stick. The pi4 will reboot in 15 seconds.

### Version

6.5.5

### Node-RED Version

2.2.2

### What hardware are you seeing the problem on?

Raspberry Pi

**Comment by marcus-j-davies** [comment]
Hi @WarrenEvans 

What exactly does that have to do with this project?
Shouldn't you be speaking to the Raspberry Pi Foundation / Aeotec?

**Comment by WarrenEvans** [comment]
Hi Marcus

Thank you for your reply. I have now done more testing. You are correct, the problem is with the Pi4 and the USB driver stalling the watchdog update. Thanks again for looking at this.

Have a great week
Warren Evans
