### ISSUE TITLE
`normalizedObject.label` missing for set point

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/node-red-contrib-zwave-js#232]
https://github.com/zwave-js/node-red-contrib-zwave-js/discussions/230#discussioncomment-3124817

**Comment by fabnavigator** [comment]
{"payload":{"networkId":1,"node":67,"nodeName":"sensor.1st_floor_thermostat","nodeLocation":"Living room","event":"GET_VALUE_METADATA_RESPONSE","timestamp":1657627624208,"object":{"commandClass":67,"endpoint":0,"property":"setpoint","propertyKey":1,"metadata":{"type":"number","readable":true,"writeable":true,"unit":"°F","ccSpecific":{"setpointType":1}}}},"_msgid":"e7121e9c7fe1c85c"}
