### ISSUE TITLE
Check value type, before printing value

### ISSUE THREAD

**Issue by fabnavigator** [zwave-js/node-red-contrib-zwave-js#240]
### What happened?

Please see the attachment:

![Untitled](https://user-images.githubusercontent.com/16625904/179858944-7bd30690-6848-4142-9ae6-15b3afbbe659.png)
.

### How to reproduce?

https://devices.zwave-js.io/?jumpTo=0x0312:0xac01:0x4002:0.0

### Version

7.2.1-beta 5

### Node-RED Version

3.0.0

### What hardware are you seeing the problem on?

Raspberry Pi

**Comment by crxporter** [comment]
If you double-click it then you should be able to see the object. I understand this is expected behavior in the UI as it would take too much effort and space to show all of the details for all of the complex cc's than exists in the ui panel. 

Messages with that cc should also show the full object.

**Comment by crxporter** [comment]
Here's an example of what I get when I double click one of mine:

![Screen Shot 2022-07-19 at 6 14 24 PM](https://user-images.githubusercontent.com/38265886/179863712-3fb9f1e7-0360-4aa2-a5c3-7fc772cdf2e2.png)

**Comment by fabnavigator** [comment]
@crxporter Where does "[object Object]" come from? Is it hardcoded to show that, or is it some sort of an error? Can it be changed to something else?

**Comment by crxporter** [comment]
It's just a JavaScript thing whenever an object is used for a thing that should be a string. It's common all over nodered debug and alert panels when (some node) tries printing a complex object, it comes out `[object Object]`

Some quick reading if you're interested:
https://careerkarma.com/blog/javascript-object-object/

**Comment by crxporter** [comment]
@marcus-j-davies perhaps there's a way to check if these are objects and when they are - kick that to some more helpful string like "click for details" ?

**Comment by fabnavigator** [comment]
Thank you.
