### ISSUE TITLE
Associations editor displays [OBJECT] [OBJECT]

### ISSUE THREAD

**Issue by lurendrejer** [zwave-js/node-red-contrib-zwave-js#245]
### How can we help?

When adding associations i cannot select anything.

The popup just displays: [OBJECT] [OBJECT] - and if I click 'Add' it creates an association to node1 endpoint 1.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/30922656/181743237-e3842c62-5bc1-418b-aae6-255e85bef895.png">

### Version

Latest

### Node-RED Version

3.0.1

**Comment by crxporter** [comment]
May be related to #240

**Comment by lurendrejer** [comment]
@crxporter - ah, neat.

Can I do something to get 8.0.0?
I deleted an association (which works absolutely fine 👍) and would like to recreate it.

**Comment by crxporter** [comment]
8.0.0 isn't out yet - @marcus-j-davies is still working on it. Also it's still pending the final zwave js 10.0 release (which is currently beta).

I also don't know if he's fixed the `[object Object]`thing in this particular situation. Let's see what he says in a couple hours once he's done with work today...

**Comment by marcus-j-davies** [comment]
Hi @lurendrejer 

This is fixed for 8.0.0, but if you want early access.

```
cd ~/.node-red
npm install node-red-contrib-zwave-js@beta
```

or to recreate the association without  the BETA



```javascript
// omit endpoint, if it doesn't apply or is not needed
//Setting association  groups for node 34
const Source = {nodeId:34:}
const Targets = [{nodeId:35:}]
const Group = 2

let Message = {
    payload: {
        mode: "AssociationsAPI",
        method: "addAssociations",
        params: [Source, Group, Targets]
    }
}
return Message

```
See
https://github.com/zwave-js/node-red-contrib-zwave-js/wiki/Associations-API

**Comment by marcus-j-davies** [comment]
And its due to this https://github.com/zwave-js/node-red-contrib-zwave-js/issues/231
closed as duplicate

**Comment by lurendrejer** [comment]
superb!
Thank you!
