### ISSUE TITLE
Improve special CC handling in Node Functions

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/node-red-contrib-zwave-js#25]
I am not happy with my original method of translating certain parameters into the z-wave js equivalent classes - i.e. Duration.
I will change this logic, to work on CC level, instead of specific parameters

**Comment by marcus-j-davies** [comment]
@hufftheweevil,

I am ready to publish 2.0 - But I call on a favour.

I have improved the way certain params are converted to classes (required by ZWJS).
At the same time - I have bridged Meter for Managed Usage.

Do you have a meter you can test? - to ensure you can get its data using Managed?.

its detail is in the readme for Managed.

**Comment by marcus-j-davies** [comment]
Version 2.0.0 is out.

Awesome work on the UI. 👍

**Comment by hufftheweevil** [comment]
Thanks, just glad I could help out.
