### ISSUE TITLE
[Bug]: It is not possible to add "Name & Location"

### ISSUE THREAD

**Issue by KristiansBox** [zwave-js/node-red-contrib-zwave-js#252]
### What happened?

There is no input field in NodeRed version 3.0.2 (node-red-contrib-zwave-js v 7.1.2)

![grafik](https://user-images.githubusercontent.com/89543800/185683856-e60c2354-26ec-48b3-8acb-e58a9bd2417a.png)

### How to reproduce?

Add or edit name of node

### Version

7.1.2

### Node-RED Version

3.0.2

### What hardware are you seeing the problem on?

Raspberry Pi

### Relevant Z-Wave-JS log as a text file

new entrys by dialog action "save"

2022-08-19T18:38:41.766Z NDERED « [CONTROLLER] Payload received.
2022-08-19T18:38:41.767Z NDERED « [API: ControllerAPI] [Method: setNodeName]
                                  └─[params]
                                      0: 17
                                      1:
2022-08-19T18:38:41.769Z NDERED » [Node: 17] [NODE_NAME_SET] [DIRECT] Forwarding payload...
2022-08-19T18:38:41.787Z NDERED « [CONTROLLER] Payload received.
2022-08-19T18:38:41.788Z NDERED « [API: ControllerAPI] [Method: setNodeLocation]
                                  └─[params]
                                      0: 17
                                      1:
2022-08-19T18:38:41.790Z NDERED » [Node: 17] [NODE_LOCATION_SET] [DIRECT] Forwarding payload...

**Comment by marcus-j-davies** [comment]
Hi @KristiansBox,

This has been fixed in V8 - which in currently in BETA.
I'll close this in favour of https://github.com/zwave-js/node-red-contrib-zwave-js/issues/231 which is for the same issue.


if you want to BETA test - please see change log before doing so.
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/8.0.0/CHANGELOG.md.

**Comment by KristiansBox** [comment]
Hi Marcus,
how can I use the beta 3 in NodeRed? I installed the package beta 3 via npm but it is not activate in NodeRed. There ist always version 7.1.2 active.

Kristian

**Comment by marcus-j-davies** [comment]
Hi @KristiansBox  - restart Node RED, and it should apply.

**Comment by KristiansBox** [comment]
Unfortunately that does not work. Even a restart didn't help. Does version 7 have to be uninstalled beforehand?

**Comment by KristiansBox** [comment]
There are some Bugs in 3.0.2 (https://discourse.nodered.org/t/enotempty-when-installing-node-from-palette-since-nodered-3-0-directory-not-empty/65968/21)
I had to delete all folder with a dot at the first position and now is the beta active an I can change the name.
Thanks a lot. Have a nice weekend ;-)

Kristian

**Comment by marcus-j-davies** [comment]
Anytime.

When I release the 3.0.0 as stable - it should show as an update.

Have a great weekend

**Comment by KristiansBox** [comment]
No, uninstalling went automatically. At the beginning I was in the wrong folder and in between on the wrong server :')

**Comment by marcus-j-davies** [comment]
But you're all good right?

**Comment by KristiansBox** [comment]
Yes all good
