### ISSUE TITLE
Migrate to ZWave JS v7

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/node-red-contrib-zwave-js#26]
Points of interest.
 - Nodes will no longer be re-interviewed on driver restart. 🎉 
    We can now remove that (hacky) check on restart
 - Notification event changes.

**Comment by marcus-j-davies** [comment]
@hufftheweevil,

I’m am prepping 2.1 for v7 of ZWJS.

The change log notes that the Meter CC, will have some values removed - which I believe you worked around.

https://github.com/zwave-js/node-zwave-js/releases

Will your work around, now cause an exception?

**Comment by hufftheweevil** [comment]
Well how bout that. I guess I'm just ahead of my time.

It won't cause any issues. But I can remove the tooltip on the next update. No hurry.
