### ISSUE TITLE
Connecting a Homeseer Z-net ethernet controller

### ISSUE THREAD

**Issue by Mikee1234K** [zwave-js/node-red-contrib-zwave-js#271]
### How can we help?

I would like to connect a Homeseer Z-net Zwave controller. This is connected via ethernet, not USB. Is that possible ?

### Version

newest

### Node-RED Version

4.0.0

### What hardware are you using?

Windows

**Comment by marcus-j-davies** [comment]
Maybe!

Providing this Z-Net device offer the serial protocol over IP, then it may work.
Choose "Custom" in the serial port config and use **tcp://x.x.x.x:2001**.

you might need to check the correct port.

again ,if this allows serial over IP - then yes - it will work
