### ISSUE TITLE
"Network Heal Stopped" message should be changed to something like "Route Rebuilding Stopped"

### ISSUE THREAD

**Issue by fabnavigator** [zwave-js/node-red-contrib-zwave-js#286]
### What happened?

Message needs to be updated to remove "heal".

### How to reproduce?

Select "Stop Rebuilding Routes".

### Version

9.0.2

### Node-RED Version

3.1.0

### What hardware are you seeing the problem on?

Raspberry Pi

**Comment by marcus-j-davies** [comment]
Hi @fabnavigator 

Have removed the `bug` tag as its just a cosmetic change, I'll update it if/when v9 receives another update - as my aim is to try and progress with V10.

**Comment by fabnavigator** [comment]
@marcus-j-davies, Thank you.

**Comment by fabnavigator** [comment]
Thank.you.
