### ISSUE TITLE
Docs: Add Home Assistant install guide

### ISSUE THREAD

**Issue by sparky073** [zwave-js/node-red-contrib-zwave-js#40]
**Plugin Version**
Module Version 3.2.0
Driver Verstion 7.1.1

**Platform**
Debian 10

I've successfully installed node-red-contrib-zwave-js in my Home Assistant environment.  But cannot set it up properly.  I think the Serial Port field should give me options but it isn't.  

I read here to try: npm install serialport, but that didn't help.

Any suggestions would be very much appreciated.  Thanks.

**Comment by marcus-j-davies** [comment]
see this comment: https://github.com/zwave-js/node-red-contrib-zwave-js/issues/17#issuecomment-772894575
the HA environment, has issues installing serial port the normal way for some reason.

I don't use HA, so not sure what causes it.

**Comment by marcus-j-davies** [comment]
@sparky073 

Ok,
Having just fired up a new install of HA - I wanted to tackle this (we have had a few reports).
it seems to install this node via the HA Node Red add-on, you need to take a different approach.

1: Install Node Red into HA as normal (if not already)
2: Do not use the pallete menu!
2: Edit the add on Configuration  (specifically the `system_packages` and the `npm_packages` section)


```yaml
system_packages:
  - make
  - python3
  - g++
  - gcc
  - linux-headers
  - udev
npm_packages:
  - serialport
  - node-red-contrib-zwave-js
```

Then restart Node Red. This approach worked perfectly, and I was able to use it as normal.

@hufftheweevil,
I'll get this added to the read me.

**Comment by marcus-j-davies** [comment]
Guide added to our dev branch,
https://github.com/zwave-js/node-red-contrib-zwave-js/tree/dev#home-assistant-install

**Comment by sparky073** [comment]
Marcus thank you so much for the quick response. 

I uninstalled the add-on from the Pallette menu, then changed the Node Red Config file according to your instructions and re-started Node Red.  This got me further than before!

In the _zwave js node_, I now get a list of serial ports in the drop down box. However, no matter what I try the node is stuck on 'Starting Z-Wave Driver..' and the _zwave device node_ is stuck on 'ZWave Node: Select Node not ready'.  The debug message is "ZWaveError: The controller is not yet ready!"

My ZWave JS config file is:

device: >-
  /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300CE3-if00-port0
network_key: 8cXXXXXXXXXXXXXXXXb7

I've entered the device path into the serial port field (Custom Path).  I've also tried /dev/ttyUSB0, which is the proper port.  Still no luck.

The network key was converted hex format, so I don't think that's the issue.

Do you have any idea what's wrong or what else I can try?  I don't know what else I can try.

**Comment by marcus-j-davies** [comment]
The network key should be. [0x01, 0x02, 0x03] - not a hex string.

**Comment by marcus-j-davies** [comment]
If you are still getting issues, if you can create a debug log for me?

**Comment by sparky073** [comment]
I think my network key is formatted properly.  What to you think?

![Capture1](https://user-images.githubusercontent.com/16310031/114033404-3b500080-984b-11eb-9ad9-2c87041172cb.JPG)
![Capture2](https://user-images.githubusercontent.com/16310031/114033417-3e4af100-984b-11eb-8c7c-f1bd83ed4b87.JPG)

I'll send you a debug log this afternoon.  Again, I appreciate your assistance.

**Comment by marcus-j-davies** [comment]
Ok,

It looks as if the serial port is already in use: first error in the debug window.
do you have anything else trying to use it - as that will be a problem

**Comment by sparky073** [comment]
That’s the port for my Nortek ZWave dongle. I would expect it to be in use.

**Comment by marcus-j-davies** [comment]
Only 1 application can make use of the serial port  - serial ports can't be shared between applications
this node of course is trying to get at it, and in your case something else has a lock on it (or using it)

Do you have any other z-wave application running (other than this node)

**Comment by marcus-j-davies** [comment]
Just out of interest, you are not trying to use this with other z-wave plugins?
if so - that's the reason.

This node is designed to host the entire z-wave stack in node red, and isn't designed to be used with others.

If not, you need to find out what is using that serial port.

**Comment by sparky073** [comment]
Getting out of my comfort zone here, let me explain my setup.  

I have HA running on a PC imaged with Debian 10.  I bought a Nortek USB stick to give me Zigbee and ZWave interfaces to my devices.  Within HA, I have installed the Zigbee and Z-Wave JS integrations, to expose these devices to my HA instance.

Since I'm trying to centralize my automations within Node Red, I wanted to also install the node-red-contrib-zwave-js add-on to give me control of my Z-Wave devices from Node Red.

What I think I'm hearing is that I can't have both the node-red-contrib-zwave-js add-on and the Z-Wave JS integration running at the same time.  They are competing for the same serial port.  Is this correct?

**Comment by marcus-j-davies** [comment]
Yup - I was suspicious  😆 

Sadly - You're  not the only one that this has happen to (and likely not the last)
This is why I have now put it up on the read me.

This node uses Z-Wave JS, and a short while ago, HA made the switch to the same backend library (probably where the confusion is)

each want's to instantiate  their communication  with the serial port.

if you want Z-Wave to be managed in node-red (and not in HA), this node will work.
but if you want to manage z-wave in HA - you will not be able to use this node.

Again fighting over the serial port - go with what ever is easier.

**Comment by sparky073** [comment]
Makes sense, I've learned a lot.  Thank you for your support.

Here's the link to the stick, single USB port 2 radios

https://www.nortekcontrol.com/products/2gig/husbzb-1-gocontrol-quickstick-combo/

**Comment by marcus-j-davies** [comment]
Closing (on assumption, this is not what you need) 👍
