### ISSUE TITLE
How to manual upgrade Zwave JS?

### ISSUE THREAD

**Issue by 0rsa** [zwave-js/node-red-contrib-zwave-js#42]
Hello,
Zwave JS 7.2.3 is released
What is the best/safe way to use it with node-red-contrib-zwave-js?
Thank you

**Comment by marcus-j-davies** [comment]
Hey.

Give me 10 minutes, I'll update the library now.

**Comment by marcus-j-davies** [comment]
@0rsa,

3.2.2  With the latest Z-Wave JS is now released.
within an hour Node-Red should show there is an update available within in the pallete menu.

**Comment by marcus-j-davies** [comment]
Closing  - assuming all ok?

If you actually want to slipstream a different version of Z-Wave JS, it requires some command line work, and building Z-Wave JS from source.

See (you will need yarn installed)
https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github
