### ISSUE TITLE
Add controller status messages?

### ISSUE THREAD

**Issue by crxporter** [zwave-js/node-red-contrib-zwave-js#47]
I'm working on migrating from zwavejs2mqtt (I'm almost ready!) and thought it could be nice to have controller status passed to nodered as the node status.

Screenshot from the mqtt interface:
<img width="1214" alt="Screen Shot 2021-04-29 at 2 53 01 PM" src="https://user-images.githubusercontent.com/38265886/116721214-ae5c1b00-a9a2-11eb-96d2-5fb9f7e89bec.png">

I was thinking it could probably be placed where the "All nodes ready!" Message appears?
<img width="284" alt="Screen Shot 2021-04-30 at 10 57 25 AM" src="https://user-images.githubusercontent.com/38265886/116721464-f2e7b680-a9a2-11eb-9756-51edbbbc7322.png">

I suppose the alternate option is enabling logs and just watching status there while I debug. Feel free to say "no" and close this one.

**Comment by marcus-j-davies** [comment]
Hey!

> I was thinking it could probably be placed where the "All nodes ready!" Message appears?

Not a bad idea at all, I like it, these types of events are delivered via a node message, but can see why it would be much better to have them in view also.

Z-Wave JS Logging introduced a bug as of 7.2.4 (which is now fixed)
https://github.com/zwave-js/node-zwave-js/issues/2490

Logging does not work, if the process does not have an interactive terminal (i.e running as a systemd service)
Sometime this evening I will be dropping 3.3.0 which includes the Z-Wave JS version with logging being fixed (and other enhancements)

**Comment by marcus-j-davies** [comment]
@crxporter,

Just a courtesy ping, to advise 3.3.0 has dropped (should appear in Red ~1 Hour)
This restores logging, if you need to use it for monitoring purposes.

I'll aim to include the controller status in the node for 3.3.x

3.3.0 **Deprecation Warnings**
 - Bump Z-Wave JS
 - Added new Association management methods via a new **Associations** class
 - The Managed **Association** and **AssociationGroupInfo** classes are now marked for removal.
 - Improvements/fixes to logger
 - Fixed Some UI weirdness
 - Improvements/fixes to Z-Wave Device Node

**Comment by crxporter** [comment]
Thank's for the heads up, I'm hoping to make the full switch over from mqtt this evening.

**Comment by marcus-j-davies** [comment]
Do keep me updated.
Feel free to get involved as you see fit 👍

**Comment by marcus-j-davies** [comment]
Something like this @crxporter 

![image](https://user-images.githubusercontent.com/55892693/116788668-d468e480-aaa2-11eb-9644-fdff3cb0787b.png)

**Comment by crxporter** [comment]
Very cool! 

Does it work for other controller messages? Like... inclusion, exclusion, or refresh?

Then probably back to green "ready" once it's through?

**Comment by marcus-j-davies** [comment]
yep.

it will project inclusion, exclusion , heal & interview

**Comment by marcus-j-davies** [comment]
@crxporter 

Have just dropped 3.3.1 - Which brings the Controller status Text on the controller node (amount other things)

 - Added an optional **forceUpdate** object for **Managed** mode usage. [#51](https://github.com/zwave-js/node-red-contrib-zwave-js/issues/51)
 - Added the realtime status of the controller to the Node status text. [#47](https://github.com/zwave-js/node-red-contrib-zwave-js/issues/47)
 - Z-Wave Node Name and Location are now stored on the target device (if supported, and updated)
 - Improved Controller status events to further describe the order
 - Updated the descriptions between Managed and Unmanaged Modes
 
 I want to keep this open, until you have had a chance to spool it up. Hopefully the status text is pretty clear.
  - Interviewing Status
  - Healing Status (for all nodes)
  - Include/Exclude Status

**Comment by crxporter** [comment]
It's perfect. Awesome work.

I just interviewed a node then added a new device. Very nice to see each step progressing.

**Comment by marcus-j-davies** [comment]
Good to know!

The status text goes on bit if a rant, when no cache file is found (Z-Wave JS learning what's what)
but after that, it's pretty settled.
