### ISSUE TITLE
Force Trigger VALUE_UPDATED for CC API

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/node-red-contrib-zwave-js#51]
some devices (seems to be those with > 1 endpoint.)
don't report back the updated value.

I will work around this, by enforcing a Get (if needed), and if using the CC API

@crxporter

**Comment by marcus-j-davies** [comment]
Ok,

So after looking at options, I can add an optional property in the message, lets say `forceUpdateOn` this will be a value of a property you want to trigger an update on.

The resulting message will look like.

```javascript
let Message = {
    payload: {
        node: 2,
        class: "BinarySwitch",
        operation: "Set",
        endpoint: 1,
        forceUpdateOn: "currentValue"
        params: [true]
    }
}
return Message
```

`forceUpdateOn` will cause a fetch on the identified property, and ultimately return a `VALUE_UPDATED`
making it optional, means we don't do this for devices behaving correctly - else you will get 2 events for the same thing

I think this is a very clean way.
this actually happens with the Value API internally, hence why the updates are delivered using the UI

Obviously, one can use the Value API if preferred - just a little more tedious

**Comment by crxporter** [comment]
In my case I would like to send everything through the same function node, regardless if it is a "well behaved" or a "rebel" device. So what is the damage, in regards to additional Zwave traffic, in using the force update option on all binary switch commands?

Perhaps it will be better for me to use the value API in this case. 

Alternate thought:
What if the force update is an option in the device config? So in the UI we could check a box to always force update on that device? This way we can still use the CC API as usual but the force update happens when that box is ticked.

**Comment by marcus-j-davies** [comment]
You could add a condition?

```javascript
let ForceUpdatesFor = [5, 32, 10, 19]
let MessageToController = msg

if (ForceUpdatesFor.includes(MessageToController.payload.node)) {
    MessageToController.payload.forceUpdateOn = {
        property: "currentValue"
    }
}

Return MessageToController

```
The Value API - does exactly what this will do.
The Value API can be used, you just need to store the ValueID's, and reference them.

you can them with.

```javascript
let Message = {
    payload: {
        node: 2,
        class: "Unmanaged",
        operation: "GetDefinedValueIDs"
    }
}
return Message
```

**Comment by marcus-j-davies** [comment]
>What if the force update is an option in the device config? So in the UI we could check a box to always force update on that device? This way we can still use the CC API as usual but the force update happens when that box is ticked.

Not bad - Will have to give it some thought, as to storing it for retrieval on restarts

**Comment by crxporter** [comment]
I'm remembering that the mqtt version really had a lot of duplicated messages. I wonder if it just always does a similar thing like you are suggesting.

**Comment by marcus-j-davies** [comment]
It's quite possible.

A lot of devices don't follow spec, one of which is updated values should always report back with new value.
The Value API has a finite waiting time, to allow chance for that update, and if it isn't received in time, will force a Get.

If you decide to stick to using Managed Mode (easier in my opinion).
you can just apply that `forceUpdateOn` object for specific nodes as exampled.

In  other news - I'm almost done with adding Controller status to the node status text.

**Comment by crxporter** [comment]
> The Value API has a finite waiting time, to allow chance for that update, and if it isn't received in time, will force a Get.

The value api is just sounding better and better... I'm out of bed now I think I'll run through some tests on that.

**Comment by marcus-j-davies** [comment]
Yeah - its a good API (I don't use it myself) but the node has full support for it.
It is limited however to primitive types, i.e you can't pass durations or control exotic types with it.

Binary Switches and stuff like that should be fine.

**Comment by marcus-j-davies** [comment]
Heres the guide.

https://github.com/zwave-js/node-red-contrib-zwave-js/blob/main/unmanaged.md

**Comment by marcus-j-davies** [comment]
**forceUpdate** added in 3.3.1
