### ISSUE TITLE
Log level sorting

### ISSUE THREAD

**Issue by crxporter** [zwave-js/node-red-contrib-zwave-js#62]
Version 3.7.1

This list is clearly in alphabetical order - can it be moved to order of "how many logs"? So I think on a scale from "Error" to "Silly"... I would put "Error" (fewest logs?) on top and "Silly" (most logs) on the bottom.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/38265886/120899381-0f57be00-c5f5-11eb-9304-9f347c8c2ef4.png">

**Comment by crxporter** [comment]
Let's see if I get it right?

1- Error (fewest logs)
2- Warn
3- Info
4- Verbose
5- Debug
6- Silly (most logs)

**Comment by marcus-j-davies** [comment]
Hey!

Once upon a time, it was ordered by the numerical value (which you listed )
https://github.com/winstonjs/winston#logging-levels

This was changed, to use the string values (z-wave JS, internally converts).
I had a mental tick, about not having order (visually or in code)

Log level `http` is not used in Z-Wave JS

was
```html
<option value="0">Error</option>
<option value="1">Warn</option>
<option value="2">Info</option>
<option value="4">Verbose</option>
<option value="5">Debug</option>
<option value="6">Silly</option>
```

Now
```html
<option value="debug">Debug</option>
<option value="error">Error</option>
<option value="info">Info</option>
<option value="silly">Silly</option>
<option value="verbose">Verbose</option>
<option value="warn">Warn</option>
```

I do agree however, its normal practice, to have the order based on Logging level, as apposed to someone's tick 😆

**Comment by crxporter** [comment]
I have no issue with the debug level names ... I was mostly referring to the specific drop down menu ... it would be nice to have it in order so I can be like "I want one level more or less" and just pick the one above or below the current set ...

**Comment by marcus-j-davies** [comment]
Yup.

it was in order (of log severity ) when I was using integers for the backend value, when I switched to using the strings for the backend,  I switched  to showing it alphabetically (due to my own quirks)

**Comment by crxporter** [comment]
Ah. I understand now. Carry on!

**Comment by marcus-j-davies** [comment]
for 3.8.0 (next release)
