### ISSUE TITLE
Text box not showing for all config options

### ISSUE THREAD

**Issue by crxporter** [zwave-js/node-red-contrib-zwave-js#74]
**Plugin Version**
3.8.0.

**Platform**
Raspberry pi

**Describe the bug**
When entering some config params, there is only an option for predefined options when there should also be an option for any value. For example the Aeotec 3 in 1 sensor.

User manual shows this for param 1:
![image](https://user-images.githubusercontent.com/38265886/124273232-5dcd7f00-db05-11eb-86ff-d4c1f85e64a7.png)

But node red UI shows only the option to disable:
![image](https://user-images.githubusercontent.com/38265886/124273317-776ec680-db05-11eb-9626-3626f4080c63.png)

I would propose another option in there for "Other" like this:
![image](https://user-images.githubusercontent.com/38265886/124273640-e2200200-db05-11eb-8a28-031f953cb0c9.png)

I believe it should be fine on any config param since the device will simply ignore something out of bounds, right?

**Comment by marcus-j-davies** [comment]
Yup.

Its a known bug in the UI.
A text box should appear. IF

`allowManualEntry` is set to true on a param (and it does)
however, if there are also predefined options as well as `allowManualEntry` being true, it wont show the text box.

I will take a look at this over the weekend (it should be an easy fix) - hopefully for V4
