### ISSUE TITLE
ZWave JS Upgrade

### ISSUE THREAD

**Issue by 0rsa** [zwave-js/node-red-contrib-zwave-js#75]
Hello,

I'm impacted by this issue described here: https://github.com/zwave-js/node-zwave-js/issues/2938

Can you upgrade ZWave JS, 7.8.0 (which is not the latest version) includes this fix which can maybe help me:
Detect serial disconnection, destroy driver on serial/socket failure

Thank you!

**Comment by marcus-j-davies** [comment]
@0rsa,

I am today, releasing V4 (which will include at least : 7.11.0)


There will be a need to update your messages to use a new API (but there will be sometime - very small window) the old API will still be intact.

here is a migration guide.
https://github.com/zwave-js/node-red-contrib-zwave-js/blob/dev/APIChange.md

V4 Change Log.
![image](https://user-images.githubusercontent.com/55892693/125031442-94b31000-e084-11eb-8583-ab66d4f6a046.png)

**Comment by marcus-j-davies** [comment]
V4 has been released.

https://github.com/zwave-js/node-red-contrib-zwave-js/blob/main/APIChange.md
