### ISSUE TITLE
Stuck in status "Starting Z-Wave Driver..."

### ISSUE THREAD

**Issue by elvee77** [zwave-js/node-red-contrib-zwave-js#77]
**Plugin Version**
latest (downloaded today)

**Platform**
RPI

I have the Aeotec Z-Wave Plus Z-Stick gen5 in my Pi and the zwave.js node its serial port is set to /dev/ttyAMA0
The only odd thing is that the status of the node is stuck on "Starting Z-Wave Driver...".

Is this a common isuse? Of not, I could just try a fresh image on my Pi and see if the issue persits?

**Comment by crxporter** [comment]
Have you tried /dev/ttyACM0 ? That's where my usb stick shows up on raspberry pi.

**Comment by marcus-j-davies** [comment]
As @crxporter pointed out.

`/dev/ttyAMA0` Is not right - it should be `/dev/ttyACM0` for Aeotec at least.

**Comment by elvee77** [comment]
Ok, found this as a good possible reason on why the usb stick is not showing: https://github.com/raspberrypi/linux/issues/3027
Apparently the Aeotec stick is not working on RPi4 and the workaround is using a USB-Hub. (Some USB2.0 vs 3.0 handshaking issue). I will buy a cheap hub and then check in again to confirm this was the issue!

**Comment by marcus-j-davies** [comment]
That is exactly what I do.

The Aeotec USB dongle has issues on Pi4 (I use a pound/dollar land type USB 2.0 hub), and it works great.
Please let us know if this works - and you are able to get off the ground with it and start using this node. 👍

**Comment by marcus-j-davies** [comment]
@elvee77,

Any update with your set up?
I like to keep things fresh in my mind with help requests, hence the ping.

**Comment by elvee77** [comment]
It is like magic!! Stick is detected and using the custom Node-Red menu (that is very nice by the way!) I was already able to reset the stick.

Tomorrow I am going to start playing with it.

I have 50+ Fibaro devices in my house, but the HC2 freezes from time to time. Even when I do most of the automation using Node-Red and the Fibaro API, it still freezes. So very happy to remove this buggy component in the future! This project is a very nice surprise! Thank you guys for the effort!!

**Comment by marcus-j-davies** [comment]
That's great to hear.
Please do reach out for any help required.

welcome to **node-red-contrib-zwave-js**

**Comment by Lucas68740** [comment]
Hello everyone y obtain the same errors on a raspberry pi 4 the node red is stucks at "Starting driver nodejs" and i have a dongle 7 i have try to connect the dongle on the usb 2 and or usb 3 and i have the same errors"↵↵---------------------------------------------------------------------↵Your flow credentials file is encrypted using a system-generated key.↵↵If the system-generated key is lost for any reason, your credentials↵file will not be recoverable, you will have to delete it and re-enter↵your credentials.↵↵You should set your own key using the 'credentialSecret' option in↵your settings file. Node-RED will then re-encrypt your credentials↵file using your chosen key the next time you deploy a change.↵---------------------------------------------------------------------↵"
03/03/2024 13:18:27
msg : string[129]
"[serialconfig:ccce6b9ce5924ec6] serial port /dev/ttyPKW3 error: Error: Error: No such file or directory, cannot open /dev/ttyPKW3"
03/03/2024 13:18:27
msg : string[129]
"[serialconfig:e3c8faf77aeea751] serial port /dev/ttyPKW4 error: Error: Error: No such file or directory, cannot open /dev/ttyPKW4" can some people can help me? or have the same problems
