### ISSUE TITLE
Inconsistency in endpoint/endPoint property

### ISSUE THREAD

**Issue by hufftheweevil** [zwave-js/node-red-contrib-zwave-js#8]
First off, I'm excited to see this node take off! Having Z-Wave directly in Node-RED without using other layers of communication is going to be awesome. I'm also interested in contributing to the docs and code.

For starters, I noticed that there appears to be an inconsistency with the `endpoint` property. Within the `zwave-js` library, `endpoint` has a lowercase `p`. So it is like that when inbound messages are received. However, this node requires that any outgoing messages (i.e. commands) use a capital `P`, like `endPoint`.

Is there a specific reason for this? Or should it be changed to match the main library?

**Comment by marcus-j-davies** [comment]
>For starters, I noticed that there appears to be an inconsistency with the endpoint property. Within the zwave-js library, endpoint has a lowercase p. 

No reason what so ever, other than my styling
Do you mind raising  a PR against dev to correct it?

I do agree on the consistency here.

**Comment by hufftheweevil** [comment]
Fixed with https://github.com/zwave-js/node-red-contrib-zwave-js/pull/10

**Comment by marcus-j-davies** [comment]
I will be dropping 1.3.0 a bit later, which includes (amongst other fixes) z-wave js 6.1.0.
