### ISSUE TITLE
More comprehensive "Device Node" options

### ISSUE THREAD

**Issue by crxporter** [zwave-js/node-red-contrib-zwave-js#80]
Feature request to "beef up" the options for the device node. A comprehensive solution could include these options
1. Select an individual node (current functionality)
2. Specify a node number using on the input message (not sure what this would send "out")
3. Select multiple devices (requires node number input, sends all messages from selected devices)
4. All devices (send and receive all device messages)

I think it's pretty clear for everything but (2) what would come "out" of the Device Node. Let me know if I've missed any cases.

Thanks as always!

**Comment by marcus-j-davies** [comment]
So, the full list will be.

`Individual Node` (In/Out)
`Specify In Message` (In/Out < last node id specified  in last message) <------ Slick!
`Multiple Devices` (In/Out)
`All` (In/Out))

**Comment by crxporter** [comment]
What if `Specify In Message` sends output message for all inputs it's gotten since the last time it was reset?

Send `msg.reset = true` to clear them? 

Unless you're thinking this would be more of a single device so once it starts receiving a node we are assuming that's the one to use forever?

**Comment by marcus-j-davies** [comment]
> Unless you're thinking this would be more of a single device so once it starts receiving a node we are assuming that's the one to use forever?

Almost,

It will listen for the node, that it received an input message for, if a different node id is received later, (again on input) it will now start listening for that node - so it will update and start listening for the node it last addressed

**Comment by crxporter** [comment]
> It will listen for the node, that it received an input message for, if a different node id is received later, (again on input) it will now start listening for that node - so it will update and start listening for the node it last addressed

Cool. Thinking more about it, this would probably be a good setting to use if you want it in a subflow.

**Comment by marcus-j-davies** [comment]
I will test our aim with it over the weekend.
