### ISSUE TITLE
Move to v6

### ISSUE THREAD

**Issue by hufftheweevil** [zwave-js/node-red-contrib-zwave-js#9]
Is there a plan to move to the latest and greatest `zwave-js` v6 soon? Looks like a few breaking changes that need to be addressed. I can help with the changes, if needed.

**Comment by marcus-j-davies** [comment]
Hey!

> Is there a plan to move to the latest and greatest zwave-js v6 soon?

The dev branch is in the waiting. this should have the required changes, I just haven't merged it into master yet.
master represents the current release on flows/npm etc.

>  I can help with the changes,

The more involvement, the better 👍
Raise your PR's against the dev branch

**Comment by hufftheweevil** [comment]
FYI it seems to be working well for me. Thanks for the update!
