### ISSUE TITLE
[Bug]: After pi4 power cycle, Zwave yale lock cannot be controlled 

### ISSUE THREAD

**Issue by WarrenEvans** [zwave-js/node-red-contrib-zwave-js#92]
### Contact Details (optional)

warrenevans@xtra.co.nz

### What happened?

When my power goes out on my pi4, the zwave yale lock cannot be controlled. The feedback is working, but I cannot send Commands. This can be fixed by doing a manual interview of the node. See attached screen capture showing a before and after interview. Can this be corrected with an automatic interview on power up or retaining the interview information through a power cycle?

If you need I have a full log of the start up from first power on with at the end the manual interview that fixed the problem. The file is 62MB, so could not be attached. I can send to you if required

![Yale lock 13-8-2021](https://user-images.githubusercontent.com/6274973/129281294-c20100a6-c35c-4c43-a406-4d7765cf6e01.gif)

### How to reproduce?

Please list steps to reproduce. If the problem is hardware-specific, please list which devices are affected.

### Version

4.3.0

### Node-RED Version

1.3.5

### What hardware are you seeing the problem on?

Raspberry Pi

### Relevant Z-Wave-JS log output

```shell
Log is to big to paste here. I can email if required.
```

**Comment by marcus-j-davies** [comment]
Hello,

Define "power cycle" is that shutting down the pi correctly or just pulling the power.

**Comment by AlCalzone** [comment]
I'd need to see a logfile - you can just upload it here by drag&drop.
Please try to limit it to the power cycle and subsequent driver start where things go wrong.

**Comment by marcus-j-davies** [comment]
@WarrenEvans,

As above, we do need the log (focused on the power cycle and start up).
It might also be helpful, to attach your cache files (Before the power cycle)

These can normally be found here:
`/home/pi/.node-red/zwave-js-cache/<HomeID>.json`
`/home/pi/.node-red/zwave-js-cache/<HomeID>.values.jsonl`

**Comment by WarrenEvans** [comment]
Marcus

 

I have attached the files requested.

 

Regards

Warren Evans

**Comment by WarrenEvans** [comment]
Marcus

 

I normally use shutdown while testing.

 

Regards

Warren Evans

**Comment by marcus-j-davies** [comment]
@WarrenEvans,

There are no files attached.

**Comment by AlCalzone** [comment]
Attaching files doesn't work via e-mail. You'll have to open the issue and upload them via drag and drop.

**Comment by WarrenEvans** [comment]
Marcus

 

I have attached the log.

 

Regards

Warren Evans

**Comment by WarrenEvans** [comment]
Marcus

 

I have attached the next file.

 

Regards

Warren Evans

**Comment by WarrenEvans** [comment]
Marcus

 

This is the last file. I hope you got them all.

 

Regards

Warren Evans

**Comment by AlCalzone** [comment]
@WarrenEvans Attaching files doesn't work via e-mail. You'll have to open the issue and upload them via drag and drop.

**Comment by marcus-j-davies** [comment]
@WarrenEvans,
As mentioned, you need to do this within Github, and not via a reply to email.

Drag the files **into** the comment box

**Comment by WarrenEvans** [comment]
Sorry for getting this in the wrong place. I have attached the log and the other 2 file.
[zwave-js-log.zip](https://github.com/zwave-js/node-red-contrib-zwave-js/files/6995637/zwave-js-log.zip)

**Comment by AlCalzone** [comment]
Looks like the driver tries to communicate without encryption. Likely the power out broke your `<homeid>.json` cache file, where the security status is stored.
This might be the thing I fixed in v8.0.6 https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md#806-2021-07-28 or this might mean that we need to do https://github.com/zwave-js/node-zwave-js/issues/3091 to solve it.

**Comment by marcus-j-davies** [comment]
@WarrenEvans,

I have V5 of this node being released very soon, a few users are using the beta.
This of course, includes the most recent version of z-wave js.

You can install the beta, to see if this fixes the issue you're seeing.

Make sure you log into terminal as a user that has read/write access to `.node-red`

In the `.node-red` directory.
`npm install --production node-red-contrib-zwave-js@beta`

Be warned however! V5 removes an old API model (deprecated in v4)
see https://github.com/zwave-js/node-red-contrib-zwave-js/blob/dev/APIChange.md if you're not already using the new model

**Comment by marcus-j-davies** [comment]
V5 has been released.

if you continue to get issues,
please re-open providing a fresh set of log.
