### ISSUE TITLE
[Feature]: Add a Capability to Filter Events/Status from a Device in the Node

### ISSUE THREAD

**Issue by thk-socal** [zwave-js/node-red-contrib-zwave-js#98]
### What is your idea?

Within the zwave-device node, it would be advantageous to be able to filter events by ValueID after picking a zwave device or devices. 

As an example, choosing a contact sensor, or sensors, and then being able to have the node filter on only events that are notifications of the contact sensor changing state. This would provide a simpler event message to feed into other flows for quicker creation of automation and monitoring of zwave devices. This could also work for any value from the devices that change.

### Any more details?

If this is specific to some hardware or specific software version, please explain here.

### Version

5.0.0

### Node-RED Version

2.0.5

**Comment by crxporter** [comment]
Exhibit A:
![image](https://user-images.githubusercontent.com/38265886/130495284-2d9c15a1-7d00-4ef5-b906-cbf637492876.png)
